"""Initial Migration

Revision ID: 16f4bfae99d1
Revises: 6f934d6f71c5
Create Date: 2019-03-02 12:40:45.020567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f4bfae99d1'
down_revision = '6f934d6f71c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('Comment', sa.String(length=255), nullable=True))
    op.drop_column('comments', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('comments', 'Comment')
    # ### end Alembic commands ###
