"""update email column

Revision ID: 258f821ce7c2
Revises: def2a5330820
Create Date: 2019-03-04 15:42:44.709566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258f821ce7c2'
down_revision = 'def2a5330820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subsribes', sa.Column('email', sa.String(length=255), nullable=True))
    op.drop_column('subsribes', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subsribes', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('subsribes', 'email')
    # ### end Alembic commands ###
