"""Initial Migration

Revision ID: f249fe3d2858
Revises: 16f4bfae99d1
Create Date: 2019-03-02 15:29:08.379740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f249fe3d2858'
down_revision = '16f4bfae99d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.String(length=255), nullable=True))
    op.drop_column('comments', 'Comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('Comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
